2020/01/14 10:25:52.129 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2020/01/14 10:25:52.159 - MainThread - cameraHandler.py.__init__.63 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2020/01/14 10:26:11.063 - MainThread - master.py.closeEvent.427 - WARNING
camera safe shutdown failed.
'Andor' object has no attribute 'dll'


2020/01/14 11:32:17.658 - MainThread - AndorFunctions.py.__init__.48 - ERROR
Andor functions dll file not found.

Traceback (most recent call last):
  File "./andorcamera\AndorFunctions.py", line 46, in __init__
    self.dll = cdll.LoadLibrary(dllpath) # note dll path must be absolute, not relative
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
2020/01/14 11:32:17.675 - MainThread - cameraHandler.py.__init__.63 - WARNING
Andor EMCCD not initialised.
'Andor' object has no attribute 'dll'


2020/01/14 11:32:27.714 - MainThread - master.py.closeEvent.427 - WARNING
camera safe shutdown failed.
'Andor' object has no attribute 'dll'


2020/01/14 13:17:08.713 - MainThread - imsaver.py.__init__.83 - WARNING
Image saver could not create directory: X:\Sequence Log\2020\January\14
 Using current directory instead
[WinError 5] Access is denied: 'X:\\Sequence Log\\2020\\January\\14'


2020/01/14 16:46:25.563 - MainThread - settingsgui.py.reset_analyses.628 - WARNING
While creating new analysers: there are 3 image indices for the 4 image analysers.



2020/01/14 16:57:21.754 - MainThread - settingsgui.py.reset_analyses.628 - WARNING
While creating new analysers: there are 2 image indices for the 4 image analysers.



